In [95]:
import requests
import os
import shutil
import time

In [210]:
years = list(range(1991, 2024))
url_base = "https://www.basketball-reference.com/awards/awards_{}.html"

In [109]:
for year in years: 
    url = url_base.format(year)
    data = requests.get(url)
    with open("mvps/{}.html".format(year), "w+", encoding = "utf-8") as f:
        f.write(data.text)

In [111]:
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO

In [ ]:
#Testing Opening Files

with open("mvps/1991.html", encoding = "utf-8") as f:
        page = f.read()
soup = BeautifulSoup(page, 'html.parser')
soup.find('tr', class_="over_header").decompose()
mvp_table = soup.find_all(id="mvp")[0]
tables = pd.read_html(StringIO(str(mvp_table)))
mvp_1991 = tables[0]
mvp_1991

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Michael Jordan,27,CHI,77,891,960,0.928,82,37.0,31.5,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321
1,2,Magic Johnson,31,LAL,10,497,960,0.518,79,37.1,19.4,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251
2,3,David Robinson,25,SAS,6,476,960,0.496,82,37.7,25.6,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264
3,4,Charles Barkley,27,PHI,2,222,960,0.231,67,37.3,27.6,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258
4,5,Karl Malone,27,UTA,0,142,960,0.148,82,40.3,29.0,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225
5,6,Clyde Drexler,28,POR,1,75,960,0.078,82,34.8,21.5,6.7,6.0,1.8,0.7,0.482,0.319,0.794,12.4,0.209
6,7,Kevin Johnson,24,PHO,0,32,960,0.033,77,36.0,22.2,3.5,10.1,2.1,0.1,0.516,0.205,0.843,12.7,0.220
7,8,Dominique Wilkins,31,ATL,0,29,960,0.030,81,38.0,25.9,9.0,3.3,1.5,0.8,0.470,0.341,0.829,11.4,0.177
8,9T,Larry Bird,34,BOS,0,25,960,0.026,60,38.0,19.4,8.5,7.2,1.8,1.0,0.454,0.389,0.891,6.6,0.140
9,9T,Terry Porter,27,POR,0,25,960,0.026,81,32.9,17.0,3.5,8.0,2.0,0.1,0.515,0.415,0.823,13.0,0.235
10,11,Patrick Ewing,28,NYK,0,20,960,0.021,81,38.3,26.6,11.2,3.0,1.0,3.2,0.514,0.000,0.745,10.0,0.155
11,12,John Stockton,28,UTA,0,15,960,0.016,82,37.8,17.2,2.9,14.2,2.9,0.2,0.507,0.345,0.836,14.0,0.217
12,13,Isiah Thomas,29,DET,0,11,960,0.011,48,34.5,16.2,3.3,9.3,1.6,0.2,0.435,0.292,0.782,3.4,0.098
13,14,Robert Parish,37,BOS,0,10,960,0.010,81,30.1,14.9,10.6,0.8,0.8,1.3,0.598,0.000,0.767,10.0,0.198
14,15,Joe Dumars,27,DET,0,8,960,0.008,80,38.1,20.4,2.3,5.5,1.1,0.1,0.481,0.311,0.890,9.9,0.155
15,16,Bernard King,34,WSB,0,7,960,0.007,64,37.5,28.4,5.0,4.6,0.9,0.3,0.472,0.216,0.790,3.5,0.070
16,17,Kenny Smith,25,HOU,0,5,960,0.005,78,34.6,17.7,2.1,7.1,1.4,0.1,0.520,0.363,0.844,9.0,0.161
17,18,Hakeem Olajuwon,28,HOU,0,4,960,0.004,56,36.8,21.2,13.8,2.3,2.2,3.9,0.508,0.000,0.769,8.6,0.201
18,19T,Tim Hardaway,24,GSW,0,1,960,0.001,82,39.2,22.9,4.0,9.7,2.6,0.1,0.476,0.385,0.803,9.9,0.148
19,19T,Kevin McHale,33,BOS,0,1,960,0.001,68,30.4,18.4,7.1,1.9,0.4,2.1,0.553,0.405,0.829,7.9,0.182

In [117]:
#ONLY RUN AFTER WEBSCRAPING IS SUCCESSFUL
dfs = []
for year in years:
    with open("mvps/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()

    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="over_header").decompose()
    mvp_table = soup.find_all(id="mvp")[0]
    mvp_df = pd.read_html(StringIO(str(mvp_table)))[0]
    mvp_df["Year"] = year
    dfs.append(mvp_df)

In [118]:
mvps = pd.concat(dfs)
mvps.tail()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
8,9,Stephen Curry,34,GSW,0,5,1000,0.005,56,34.7,...,6.1,6.3,0.9,0.4,0.493,0.427,0.915,7.8,0.192,2023
9,10,Jimmy Butler,33,MIA,0,3,1000,0.003,64,33.4,...,5.9,5.3,1.8,0.3,0.539,0.350,0.850,12.3,0.277,2023
10,11,De'Aaron Fox,25,SAC,0,2,1000,0.002,73,33.4,...,4.2,6.1,1.1,0.3,0.512,0.324,0.780,7.4,0.146,2023
11,12T,Jalen Brunson,26,NYK,0,1,1000,0.001,68,35.0,...,3.5,6.2,0.9,0.2,0.491,0.416,0.829,8.7,0.175,2023
12,12T,Ja Morant,23,MEM,0,1,1000,0.001,61,31.9,...,5.9,8.1,1.1,0.3,0.466,0.307,0.748,6.0,0.148,2023

In [119]:
mvps.to_csv("mvps.csv")

In [ ]:
url_players = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"
#Used selenium chromedriver instead for webscraping so this code is not needed
# for year in year:
#     url = url_players.format(year)
    
#     data = requests.get(url)
    
#     with open("players/{}.html".format(year), "w+", encoding = "utf-8") as f:
#         f.write(data.text)

In [151]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service

In [203]:
service = Service(executable_path="./chromedriver.exe")
driver = webdriver.Chrome(service=service)

In [190]:
for year in years:
    url = url_players.format(year)

    driver.get(url)
    driver.execute_script("window.scrollTo(1, 5000)")
    time.sleep(2)
    html = driver.page_source
    with open("players/{}.html".format(year), "w+", encoding = "utf-8") as f:
        f.write(html)

In [193]:
dfs = []
for year in years:
    with open("players/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    player_table = soup.find_all(id="per_game_stats")[0]
    player_df = pd.read_html(StringIO(str(player_table)))[0]
    player_df["Year"] = year
    dfs.append(player_df)

In [195]:
players = pd.concat(dfs)
players.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Year
0,1,Michael Jordan,27,CHI,SG,82,82,37.0,12.1,22.4,...,4.6,6.0,5.5,2.7,1.0,2.5,2.8,31.5,"MVP-1,DPOY-7,AS,NBA1",1991
1,2,Karl Malone,27,UTA,PF,82,82,40.3,10.3,19.6,...,8.9,11.8,3.3,1.1,1.0,3.0,3.3,29.0,"MVP-5,AS,NBA1",1991
2,3,Bernard King,34,WSB,SF,64,64,37.5,11.1,23.6,...,3.2,5.0,4.6,0.9,0.3,4.0,2.9,28.4,"MVP-16,AS,NBA3",1991
3,4,Charles Barkley,27,PHI,SF,67,67,37.3,9.9,17.4,...,6.3,10.1,4.2,1.6,0.5,3.1,2.6,27.6,"MVP-4,AS,NBA1",1991
4,5,Patrick Ewing,28,NYK,C,81,81,38.3,10.4,20.3,...,8.8,11.2,3.0,1.0,3.2,3.6,3.5,26.6,"MVP-11,DPOY-7,AS,NBA2",1991

In [197]:
players.to_csv("players.csv")

In [ ]:
url_teams = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"
for year in years:
    url = url_teams.format(year)
    data = requests.get(url)
    with open("teams/{}.html".format(year), "w+", encoding = "utf-8") as f:
        f.write(data.text)

In [212]:
dfs = []
for year in years:
    with open("teams/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(StringIO(str(e_table)))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    dfs.append(e_df)
    
    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(StringIO(str(w_table)))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    dfs.append(w_df)

In [214]:
teams = pd.concat(dfs)
teams.head()

    W   L  W/L%    GB   PS/G   PA/G    SRS  Year                 Team
0  56  26  .683     —  111.5  105.7   5.22  1991      Boston Celtics*
1  44  38  .537  12.0  105.4  105.6  -0.39  1991  Philadelphia 76ers*
2  39  43  .476  17.0  103.1  103.3  -0.43  1991     New York Knicks*
3  30  52  .366  26.0  101.4  106.4  -4.84  1991   Washington Bullets
4  26  56  .317  30.0  102.9  107.5  -4.53  1991      New Jersey Nets

In [215]:
teams.to_csv("teams.csv")